name: fluttersample_2025
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  pointycastle: ^3.7.4
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.0
  mobile_scanner: ^3.0.0
  qr_flutter: ^4.1.0
  grpc: ^4.0.0
  protobuf: ^4.0.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  ffi: ^2.1.0
  faker: ^2.1.0
  flutter_ble_peripheral: ^1.2.6
  flutter_blue_plus: ^2.0.2
  permission_handler: ^11.3.1
  uuid: ^4.5.1
  flutter_launcher_icons: ^0.13.1
  network_info_plus: ^6.1.0
  geolocator: ^14.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  ffigen: ^11.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Medium.ttf

ffigen:
  name: NativeKeyBindings
  description: Bindings for the native key derivation library.
  output: 'lib/native_key_bindings.dart'
  headers:
    entry-points:
      - 'src/native/key_derivation.h'

flutter_icons:
  android: true
  ios: true
  image_path: assets/launcher_icon/icon.jpg
  adaptive_icon_foreground: assets/launcher_icon/icon.jpg
  adaptive_icon_background: "#000000"