// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for the native key derivation library.
class NativeKeyBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  NativeKeyBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  NativeKeyBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
      ) : _lookup = lookup;

  // ... (既存の定義) ...

  int generate_master_key(ffi.Pointer<ffi.Uint8> out_master_key_32b) {
    return _generate_master_key(out_master_key_32b);
  }

  late final _generate_master_keyPtr =
  _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Uint8>)>>(
    'generate_master_key',
  );
  late final _generate_master_key =
  _generate_master_keyPtr.asFunction<int Function(ffi.Pointer<ffi.Uint8>)>();

  int derive_keypair_from_timestamp(
      ffi.Pointer<ffi.Uint8> master_key,
      int timestamp_ms,
      int slot_ms,
      ffi.Pointer<ffi.Uint8> out_priv_key_32b,
      ffi.Pointer<ffi.Uint8> out_pub_key_33b,
      ) {
    return _derive_keypair_from_timestamp(
      master_key,
      timestamp_ms,
      slot_ms,
      out_priv_key_32b,
      out_pub_key_33b,
    );
  }

  late final _derive_keypair_from_timestampPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              ffi.Pointer<ffi.Uint8>,
              ffi.Uint64,
              ffi.Uint64,
              ffi.Pointer<ffi.Uint8>,
              ffi.Pointer<ffi.Uint8>)>>('derive_keypair_from_timestamp');
  late final _derive_keypair_from_timestamp =
  _derive_keypair_from_timestampPtr.asFunction<
      int Function(ffi.Pointer<ffi.Uint8>, int, int,
          ffi.Pointer<ffi.Uint8>, ffi.Pointer<ffi.Uint8>)>();

  int create_ring_signature(
      ffi.Pointer<ffi.Char> msg,
      int msg_len,
      ffi.Pointer<ffi.Uint8> signer_priv_key_32b,
      ffi.Pointer<ffi.Uint8> ring_pub_keys,
      int ring_size,
      ffi.Pointer<ffi.Uint8> out_signature,
      ) {
    return _create_ring_signature(
      msg,
      msg_len,
      signer_priv_key_32b,
      ring_pub_keys,
      ring_size,
      out_signature,
    );
  }

  late final _create_ring_signaturePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Size,
              ffi.Pointer<ffi.Uint8>,
              ffi.Pointer<ffi.Uint8>,
              ffi.Int,
              ffi.Pointer<ffi.Uint8>)>>('create_ring_signature');
  late final _create_ring_signature =
  _create_ring_signaturePtr.asFunction<
      int Function(
          ffi.Pointer<ffi.Char>,
          int,
          ffi.Pointer<ffi.Uint8>,
          ffi.Pointer<ffi.Uint8>,
          int,
          ffi.Pointer<ffi.Uint8>)>();

  // --- ★ここから新しい定義★ ---

  /// @brief リング署名を検証する。
  int verify_ring_signature(
      ffi.Pointer<ffi.Char> msg,
      int msg_len,
      ffi.Pointer<ffi.Uint8> signature,
      ffi.Pointer<ffi.Uint8> ring_pub_keys,
      int ring_size,
      ) {
    return _verify_ring_signature(
      msg,
      msg_len,
      signature,
      ring_pub_keys,
      ring_size,
    );
  }

  late final _verify_ring_signaturePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Size,
              ffi.Pointer<ffi.Uint8>,
              ffi.Pointer<ffi.Uint8>,
              ffi.Int)>>('verify_ring_signature');
  late final _verify_ring_signature = _verify_ring_signaturePtr.asFunction<
      int Function(ffi.Pointer<ffi.Char>, int, ffi.Pointer<ffi.Uint8>,
          ffi.Pointer<ffi.Uint8>, int)>();

  /// ECDSA チャレンジ署名 (secp256r1, 署名は r||s の 64バイト)
  ///
  /// C 側シグネチャ:
  /// int ecdsa_sign_challenge(
  ///   const uint8_t* priv_key_32b,
  ///   const uint8_t* msg,
  ///   uint32_t msg_len,
  ///   uint8_t* out_sig64
  /// );
  int ecdsa_sign_challenge(
      ffi.Pointer<ffi.Uint8> priv_key_32b,
      ffi.Pointer<ffi.Uint8> msg,
      int msg_len,
      ffi.Pointer<ffi.Uint8> out_sig64,
      ) {
    return _ecdsa_sign_challenge(
      priv_key_32b,
      msg,
      msg_len,
      out_sig64,
    );
  }

  /// ECDSA チャレンジ検証 (secp256r1, 署名は r||s の 64バイト)
  ///
  /// C 側シグネチャ:
  /// int ecdsa_verify_challenge(
  ///   const uint8_t* pub_key_33b,
  ///   const uint8_t* msg,
  ///   uint32_t msg_len,
  ///   const uint8_t* sig64
  /// );
  int ecdsa_verify_challenge(
      ffi.Pointer<ffi.Uint8> pub_key_33b,
      ffi.Pointer<ffi.Uint8> msg,
      int msg_len,
      ffi.Pointer<ffi.Uint8> sig64,
      ) {
    return _ecdsa_verify_challenge(
      pub_key_33b,
      msg,
      msg_len,
      sig64,
    );
  }
  // C: int ecdsa_sign_challenge(
  //      const uint8_t* priv_key_32b,
  //      const uint8_t* msg,
  //      uint32_t msg_len,
  //      uint8_t* out_sig64);
  late final _ecdsa_sign_challengePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              ffi.Pointer<ffi.Uint8>, // priv_key_32b
              ffi.Pointer<ffi.Uint8>, // msg
              ffi.Uint32,             // msg_len
              ffi.Pointer<ffi.Uint8>, // out_sig64 (64 bytes)
              )>>('ecdsa_sign_challenge');

  late final _ecdsa_sign_challenge =
  _ecdsa_sign_challengePtr.asFunction<
      int Function(
          ffi.Pointer<ffi.Uint8>,
          ffi.Pointer<ffi.Uint8>,
          int,
          ffi.Pointer<ffi.Uint8>,
          )>();

  // C: int ecdsa_verify_challenge(
  //      const uint8_t* pub_key_33b,
  //      const uint8_t* msg,
  //      uint32_t msg_len,
  //      const uint8_t* sig64);
  late final _ecdsa_verify_challengePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              ffi.Pointer<ffi.Uint8>, // pub_key_33b
              ffi.Pointer<ffi.Uint8>, // msg
              ffi.Uint32,             // msg_len
              ffi.Pointer<ffi.Uint8>, // sig64 (64 bytes)
              )>>('ecdsa_verify_challenge');

  late final _ecdsa_verify_challenge =
  _ecdsa_verify_challengePtr.asFunction<
      int Function(
          ffi.Pointer<ffi.Uint8>,
          ffi.Pointer<ffi.Uint8>,
          int,
          ffi.Pointer<ffi.Uint8>,
          )>();


// --- ★ここまで新しい定義★ ---
}
