// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for the native key derivation library.
class NativeKeyBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  NativeKeyBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  NativeKeyBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
      ) : _lookup = lookup;

  // ... (既存のWindows向け定義などがあれば、そのまま残してください) ...
  // ★ ffigenが生成した不要な定義は削除しても構いません

  int generate_master_key(ffi.Pointer<ffi.Uint8> out_master_key_32b) {
    return _generate_master_key(out_master_key_32b);
  }

  late final _generate_master_keyPtr =
  _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Uint8>)>>(
    'generate_master_key',
  );
  late final _generate_master_key =
  _generate_master_keyPtr.asFunction<int Function(ffi.Pointer<ffi.Uint8>)>();

  int derive_keypair_from_timestamp(
      ffi.Pointer<ffi.Uint8> master_key,
      int timestamp_ms,
      int slot_ms,
      ffi.Pointer<ffi.Uint8> out_priv_key_32b,
      ffi.Pointer<ffi.Uint8> out_pub_key_65b,
      ) {
    return _derive_keypair_from_timestamp(
      master_key,
      timestamp_ms,
      slot_ms,
      out_priv_key_32b,
      out_pub_key_65b,
    );
  }

  late final _derive_keypair_from_timestampPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              ffi.Pointer<ffi.Uint8>,
              ffi.Uint64,
              ffi.Uint64,
              ffi.Pointer<ffi.Uint8>,
              ffi.Pointer<ffi.Uint8>)>>('derive_keypair_from_timestamp');
  late final _derive_keypair_from_timestamp =
  _derive_keypair_from_timestampPtr.asFunction<
      int Function(ffi.Pointer<ffi.Uint8>, int, int,
          ffi.Pointer<ffi.Uint8>, ffi.Pointer<ffi.Uint8>)>();

  // --- ★ここから新しい定義★ ---

  int create_ring_signature(
      ffi.Pointer<ffi.Char> msg,
      int msg_len, // ffi.SizeはIntPtrと同じサイズなのでintで代用可能
      ffi.Pointer<ffi.Uint8> signer_priv_key_32b,
      ffi.Pointer<ffi.Uint8> ring_pub_keys,
      int ring_size,
      ffi.Pointer<ffi.Uint8> out_signature,
      ) {
    return _create_ring_signature(
      msg,
      msg_len,
      signer_priv_key_32b,
      ring_pub_keys,
      ring_size,
      out_signature,
    );
  }

  late final _create_ring_signaturePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Size,
              ffi.Pointer<ffi.Uint8>,
              ffi.Pointer<ffi.Uint8>,
              ffi.Int,
              ffi.Pointer<ffi.Uint8>)>>('create_ring_signature');
  late final _create_ring_signature =
  _create_ring_signaturePtr.asFunction<
      int Function(
          ffi.Pointer<ffi.Char>,
          int,
          ffi.Pointer<ffi.Uint8>,
          ffi.Pointer<ffi.Uint8>,
          int,
          ffi.Pointer<ffi.Uint8>)>();

// --- ★ここまで新しい定義★ ---
}

// Cの 'size_t' はDartの 'int' に対応
typedef size_t = ffi.IntPtr;
